name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "TODO: Build frontend"

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "TODO: Build frontend"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "TODO: Deploy containers"
